//u20212200570 Jhon Mairo Vanegas Olaya
//u20212199873 Julian David Ordoñez Martinez
package view;

import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Memorandum;
import persistence.MemorandumDAOImp;

/**
 *
 * @author Mario
 */
public class Memorandum extends javax.swing.JFrame {

    /**
     * Creates new form Memorandum
     */
    public Memorandum() {
        initComponents();
        this.setLocationRelativeTo(null);
        Aviso_EMAILS.setVisible(false);
    }

    public void cleanAll() {
        MemorandumDATE.setText("");
        MemorandumADDRESSEE.setText("");
        MemorandumTHEME.setText("");
        MemorandumMESSAGE.setText("");
        MemorandumSIGNING.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MEMORANDUM = new javax.swing.JLabel();
        jskjjkakso = new javax.swing.JLabel();
        MemorandumDATE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MemorandumADDRESSEE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MemorandumTHEME = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemorandumMESSAGE = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        MemorandumSIGNING = new javax.swing.JTextField();
        MemorandumSAVE = new javax.swing.JButton();
        MemorandumRESTART = new javax.swing.JButton();
        MemorandumCLOSE = new javax.swing.JButton();
        MemorandumEmails = new javax.swing.JLabel();
        Emails = new javax.swing.JTextField();
        Aviso_EMAILS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MEMORANDUM.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MEMORANDUM.setText("MEMORANDUM");

        jskjjkakso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jskjjkakso.setText("DATE");

        MemorandumDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorandumDATEActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ADDRESSEE");

        MemorandumADDRESSEE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorandumADDRESSEEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("THEME");

        MemorandumTHEME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorandumTHEMEActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("MESSAGE");

        MemorandumMESSAGE.setColumns(20);
        MemorandumMESSAGE.setRows(5);
        jScrollPane1.setViewportView(MemorandumMESSAGE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("SIGNING");

        MemorandumSIGNING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorandumSIGNINGActionPerformed(evt);
            }
        });

        MemorandumSAVE.setText("SAVE");
        MemorandumSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorandumSAVEActionPerformed(evt);
            }
        });

        MemorandumRESTART.setText("RESTART");
        MemorandumRESTART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorandumRESTARTActionPerformed(evt);
            }
        });

        MemorandumCLOSE.setText("CLOSE");
        MemorandumCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemorandumCLOSEActionPerformed(evt);
            }
        });

        MemorandumEmails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MemorandumEmails.setText("EMAILS");

        Emails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailsActionPerformed(evt);
            }
        });
        Emails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailsKeyReleased(evt);
            }
        });

        Aviso_EMAILS.setForeground(new java.awt.Color(255, 0, 0));
        Aviso_EMAILS.setText("CORREO INCORRECTO**");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MemorandumEmails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Aviso_EMAILS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MemorandumSAVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MemorandumRESTART)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MemorandumCLOSE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MEMORANDUM)
                                    .addGap(174, 174, 174)
                                    .addComponent(jskjjkakso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MemorandumDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(MemorandumADDRESSEE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MemorandumTHEME, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(MemorandumSIGNING)))
                    .addComponent(Emails, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MEMORANDUM)
                    .addComponent(jskjjkakso)
                    .addComponent(MemorandumDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MemorandumADDRESSEE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MemorandumTHEME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MemorandumSIGNING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemorandumEmails)
                    .addComponent(Emails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemorandumRESTART)
                    .addComponent(MemorandumSAVE)
                    .addComponent(MemorandumCLOSE)
                    .addComponent(Aviso_EMAILS))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void MemorandumDATEActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void MemorandumADDRESSEEActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void MemorandumTHEMEActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void MemorandumSIGNINGActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void MemorandumSAVEActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try {
            MemorandumDAOImp memorandumDAOImp = new MemorandumDAOImp();
            Memorandum memorandum = new Memorandum();
            memorandum.setDate((MemorandumDATE.getText()));
            memorandum.setaddressee(MemorandumADDRESSEE.getText());
            memorandum.setTheme(MemorandumADDRESSEE.getText());
            memorandum.setmessage(MemorandumMESSAGE.getText());
            String msg = memorandumDAOImp.addMemorandum(memorandum);
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, msg);
            this.cleanAll();
        } catch (Exception e) {
        }
    }                                              

    private void MemorandumRESTARTActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        this.cleanAll();
    }                                                 

    private void MemorandumCLOSEActionPerformed(java.awt.event.ActionEvent evt) {                                                
        System.exit(0);
    }                                               

    private void EmailsActionPerformed(java.awt.event.ActionEvent evt) {                                       

    }                                      

    private void EmailsKeyReleased(java.awt.event.KeyEvent evt) {                                   

           if (Verificar_Emails(Emails.getText())) {
            Aviso_EMAILS.setVisible(false);
        }
           else{
           Aviso_EMAILS.setVisible(true);
           }

    }                                  

    public boolean Verificar_Emails(String Correo) {
        Pattern patron = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)+*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        Matcher mat = patron.matcher(Correo);

        if (mat.find()) {

            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memorandum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memorandum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memorandum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memorandum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view.Memorandum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Aviso_EMAILS;
    private javax.swing.JTextField Emails;
    private javax.swing.JLabel MEMORANDUM;
    private javax.swing.JTextField MemorandumADDRESSEE;
    private javax.swing.JButton MemorandumCLOSE;
    private javax.swing.JTextField MemorandumDATE;
    private javax.swing.JLabel MemorandumEmails;
    private javax.swing.JTextArea MemorandumMESSAGE;
    private javax.swing.JButton MemorandumRESTART;
    private javax.swing.JButton MemorandumSAVE;
    private javax.swing.JTextField MemorandumSIGNING;
    private javax.swing.JTextField MemorandumTHEME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jskjjkakso;
    // End of variables declaration                   

}
