//u20212200570 Jhon Mairo Vanegas Olaya
//u20212199873 Julian David Ordoñez Martinez
package view;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Reports;
import persistence.ReportsDAOImp;
/**
 *
 * @author Mario
 */
public class ReportsList extends javax.swing.JFrame {
 ArrayList<Reports> listReports = new ArrayList();
    DefaultTableModel dtmReports = new DefaultTableModel();

    public ReportsList() {
        initComponents();
        this.setLocationRelativeTo(null);
        setModelo();
    }

    public void setModelo() {
        String[] header = {"Title Page", "Rating", "Introduction", "Report Body", "Conclusion","Bibliography"};
        dtmReports.setColumnIdentifiers(header);
        ReportsTbl.setModel(dtmReports);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MemorandumModeLbl = new javax.swing.JLabel();
        ReportsDataBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportsTbl = new javax.swing.JTable();
        ReportsCloseBtn = new javax.swing.JButton();
        ReportsUpdateBtn = new javax.swing.JButton();
        ReportsDeleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REPORTS");

        MemorandumModeLbl.setText("List Mode");

        ReportsDataBtn.setText("Data");
        ReportsDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsDataBtnActionPerformed(evt);
            }
        });

        ReportsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ReportsTbl.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(ReportsTbl);

        ReportsCloseBtn.setText("Close");
        ReportsCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsCloseBtnActionPerformed(evt);
            }
        });

        ReportsUpdateBtn.setText("Update");

        ReportsDeleteBtn.setText("Delete");
        ReportsDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(MemorandumModeLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(ReportsDataBtn)))
                .addGap(0, 243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ReportsCloseBtn)
                        .addGap(75, 75, 75)
                        .addComponent(ReportsUpdateBtn)
                        .addGap(63, 63, 63)
                        .addComponent(ReportsDeleteBtn)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(229, 229, 229))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemorandumModeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportsDataBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportsDeleteBtn)
                    .addComponent(ReportsUpdateBtn)
                    .addComponent(ReportsCloseBtn))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>                        

    private void ReportsDataBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        ReportsDAOImp reportsDAOImp = new ReportsDAOImp();
        //Se traen los datos de la BD
        try {
            listReports = (ArrayList<Reports>) reportsDAOImp.listReports();
            Object[] data = new Object[dtmReports.getColumnCount()];
            int i = 1;
            dtmReports.setRowCount(0);
            for (Reports reports : listReports) {
                data[0] = reports.getTitlePage();
                data[1] = reports.getRating();
                data[2] = reports.getIntroduction();
                data[3] = reports.getReportBody();
                data[4] = reports.getConclusions();
                data[5] = reports.getBibliography();
                i++;
                dtmReports.addRow(data);
            }
            ReportsTbl.setModel(dtmReports);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }                                              

    private void ReportsCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                
        System.exit(0);
    }                                               

    private void ReportsDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int index = ReportsTbl.getSelectedRow();
        Reports reports = listReports.get(index);
        //JOptionPane.showMessageDialog(null, client.getId());
        ReportsDAOImp reportsDAOImp = new ReportsDAOImp();
        int rta = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?",
            "Remove reports Registry", JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE);
        if (rta == 0) {
            try {
                reportsDAOImp.deleteReports(reports);
                JOptionPane.showMessageDialog(null, "Deleted Reports Record");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Operation Not Performed");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operation Not Performed");
        }
        if (dtmReports.getRowCount() > 0) {
            for (int i = dtmReports.getRowCount() - 1; i > -1; i--) {
                dtmReports.removeRow(i);
            }
            try {
                var Reports = reportsDAOImp.listReports();
                Object[] data = new Object[dtmReports.getColumnCount()];
                int i = 1;
                dtmReports.setRowCount(0);
                for (Reports c : Reports) {
                    data[0] = c.getTitlePage();
                    data[1] = c.getRating();
                    data[2] = c.getIntroduction();
                    data[3] = c.getReportBody();
                    data[4] = c.getConclusions();
                    data[5] = c.getBibliography();
                    i++;
                    dtmReports.addRow(data);
                }
                ReportsTbl.setModel(dtmReports);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel MemorandumModeLbl;
    private javax.swing.JButton ReportsCloseBtn;
    private javax.swing.JButton ReportsDataBtn;
    private javax.swing.JButton ReportsDeleteBtn;
    private javax.swing.JTable ReportsTbl;
    private javax.swing.JButton ReportsUpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
